name: CD artifact

on:
    workflow_run:
        workflows: ["CI artifact"]
        types:
            - completed

jobs:
    deploy:
        runs-on: node_fe

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Create .env
              run: |
                  echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_BE=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_BE }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY }}" >> .env

            - name: Stop running containers
              run: sudo docker stop con-node_fe_nextjs || true

            - name: Remove containers
              run: sudo docker rm con-node_fe_nextjs || true

            - name: Delete old docker image
              run: sudo docker rmi vulebaolong/img-node_fe_nextjs:latest || true

            - name: Run Docker container
              run: |
                  sudo docker run -d -p 3001:3000 --name con-node_fe_nextjs vulebaolong/img-node_fe_nextjs:latest

            - name: Delete .env
              run: sudo rm -f .env || true
