name: CI artifact

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login Dockerhub
              env:
                  # Lấy giá trị từ DOCKER_USERNAME trong GitHub secrets (chứa tên người dùng DockerHub của bạn).
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                  # Lấy giá trị từ DOCKER_PASSWORD trong GitHub secrets (chứa mật khẩu hoặc token truy cập DockerHub của bạn).
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              # Chạy lệnh Docker để đăng nhập vào DockerHub với tên người dùng và mật khẩu đã được lấy từ GitHub secrets.
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Build the Docker image
              run: |
                  docker build \
                  --build-arg NEXT_PUBLIC_BASE_DOMAIN=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN }} \
                  --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }} \
                  --build-arg NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY }} \
                  -t vulebaolong/img-node_fe_nextjs:latest .

            - name: Push to DockerHub
              run: docker push vulebaolong/img-node_fe_nextjs:latest
