export const CHAT_OPENED = `CHAT_OPENED`;
export const CHAT_BUBBLE = `CHAT_BUBBLE`;
export const SOCKET_CHAT_MES = {
   CREATE_ROOM: "CREATE_ROOM",
   JOIN_ROOM: "JOIN_ROOM",
   LEAVE_ROOM: "LEAVE_ROOM",
   SEND_MESSAGE: "SEND_MESSAGE",
   NOTI_MESSAGE: "NOTI_MESSAGE",
   RELOAD_STATUS_FRIEND_SHIP: "RELOAD_STATUS_FRIEND_SHIP",
};
