export const CHAT_LIST_ITEM = `CHAT_LIST_ITEM`;
export const CHAT_LIST_BUBBLE = `CHAT_LIST_BUBBLE`;
export const SOCKET_CHAT_MES = {
   GET_LIST_MESSAGES: "GET_LIST_MESSAGES",
   CREATE_ROOM: "CREATE_ROOM",
   JOIN_ROOM: "JOIN_ROOM",
   JOIN_ROOM_GROUP: "JOIN_ROOM_GROUP",
   LEAVE_ROOM: "LEAVE_ROOM",
   SEND_MESSAGE: "SEND_MESSAGE",
   NOTI_MESSAGE: "NOTI_MESSAGE",
};
