import Provider from "@/components/provider/Provider";
import { routing } from "@/i18n/routing";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

type TProps = {
   children: React.ReactNode;
   params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: TProps) {
   const { locale } = await params;

   if (!routing.locales.includes(locale as "en" | "vi")) notFound();

   const messages = await getMessages();

   return (
      <html lang="en" {...mantineHtmlProps} suppressHydrationWarning>
         <head>
            <ColorSchemeScript />
         </head>
         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <NextIntlClientProvider messages={messages}>
               <Provider>{children}</Provider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
