name: CD artifact

on:
    workflow_run:
        workflows: ["CI artifact"]
        types:
            - completed

jobs:
    deploy:
        runs-on: node_fe

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Create .env
              run: |
                  echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY }}" >> .env

            - name: Stop running containers
              run: sudo docker stop con-fe_main || true

            - name: Remove containers
              run: sudo docker rm con-fe_main || true

            - name: Delete old docker image
              run: sudo docker rmi img-fe_main:latest || true

            - name: Load new docker image from tar
              run: sudo docker load -i img.tar

            - name: Run Docker container
              run: |
                  sudo docker run -d -p 3001:3000 --name con-fe_main img-fe_main:latest

            - name: Delete .env
              run: sudo rm -f .env || true
