name: CD docker

on:
    workflow_run:
        workflows: ["CI docker"]
        types:
            - completed

jobs:
    deploy:
        runs-on: node_fe

        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Download docker image artifact
              uses: actions/download-artifact@v4
              with:
                  name: img-node_fe_nextjs
                  path: .

            - name: Delete old .env file
              run: sudo rm -f .env || true

            - name: Create new .env file and add environment variables
              run: |
                  echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_API=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_API }}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{ secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY }}" >> .env

            - name: Stop running containers
              run: sudo docker stop cons_node_fe || true

            - name: Remove containers
              run: sudo docker rm cons_node_fe || true

            - name: Delete old docker image
              run: sudo docker rmi img-node_fe_nextjs:latest || true

            - name: Load new docker image from tar
              run: sudo docker load -i img-node_fe_nextjs.tar

            - name: Run Docker container
              run: |
                  sudo docker run -d -p 3001:3000 --name cons_node_fe img-node_fe_nextjs:latest
