name: CI_CD

on:
    push:
        branches: ["fe-main"]

jobs:
    CI_CD-project:
        runs-on: node_fe

        steps:
            - uses: actions/checkout@v4

            - name: tạo file .env
              run: |
                  echo "NEXT_PUBLIC_BASE_DOMAIN=${{secrets.NEXT_PUBLIC_BASE_DOMAIN}}" >> .env
                  echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}}" >> .env
                  echo "NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY}}" >> .env

            - name: dừng và xoá container
              run: |
                  sudo docker container stop con-fe_main || true
                  sudo docker container remove con-fe_main || true

            - name: xoá image cũ
              run: sudo docker image remove vulebaolong/img-fe_main:latest || true

            - name: Build the Docker image
              run: |
                docker build \
                --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}} \
                --build-arg NEXT_PUBLIC_BASE_DOMAIN_API=${{secrets.NEXT_PUBLIC_BASE_DOMAIN_API}} \
                --build-arg NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY=${{secrets.NEXT_PUBLIC_BASE_DOMAIN_CLOUDINARY}} \
                -t vulebaolong/img-fe_main:latest .

            - name: chạy image
              run: sudo docker compose up -d

            - name: xoá env
              run: sudo rm -f .env
